//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_ap_update
    {
        public int update_id { get; set; }
        public string update_no { get; set; }
        public int apply_id { get; set; }
        public Nullable<System.DateTime> apply_date { get; set; }
        public Nullable<System.DateTime> update_ap_date { get; set; }
        public string update_type { get; set; }
        public string urgent_description { get; set; }
        public Nullable<int> check_id { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string check_status { get; set; }
        public Nullable<System.DateTime> backtrack_date { get; set; }
        public int update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
