//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_department
    {
        public string depart_code { get; set; }
        public string depart_type { get; set; }
        public string parent_depart_code { get; set; }
        public short serial_no { get; set; }
        public string depart_name { get; set; }
        public string depart_alias { get; set; }
        public string operation_type { get; set; }
        public string enabled { get; set; }
        public string os_version { get; set; }
        public string sql_version { get; set; }
        public string iis_version { get; set; }
        public string framework_version { get; set; }
        public Nullable<int> sal_version { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> golive_date { get; set; }
        public string depart_dbname { get; set; }
        public string depart_test_dbname { get; set; }
        public string company_dbname { get; set; }
        public string business_ch { get; set; }
        public Nullable<int> operators_id { get; set; }
        public int promote_work_hours { get; set; }
        public string orgcode { get; set; }
        public Nullable<int> depart_population { get; set; }
    }
}
