//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_demand_dispatch
    {
        public int dispatch_id { get; set; }
        public int demand_id { get; set; }
        public string demand_status { get; set; }
        public int d_assigned_id { get; set; }
        public int d_assigned_to_id { get; set; }
        public Nullable<System.DateTime> dispatch_date { get; set; }
        public string dispatch_description { get; set; }
        public string processing_description { get; set; }
        public Nullable<decimal> workhours { get; set; }
        public Nullable<System.DateTime> begin_date { get; set; }
        public System.DateTime schedule_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public int update_user_id { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
