//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_menu_1100126
    {
        public string menu_code { get; set; }
        public string parent_menu { get; set; }
        public short serial_no { get; set; }
        public string menu_name { get; set; }
        public string link_url { get; set; }
    }
}
