//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_news_20201014
    {
        public int news_id { get; set; }
        public string news_kind { get; set; }
        public string depart_code { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string enabled { get; set; }
        public System.DateTime begin_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string top_news { get; set; }
        public string meta1 { get; set; }
        public string meta2 { get; set; }
        public string meta3 { get; set; }
        public int news_count { get; set; }
        public int update_user_id { get; set; }
        public System.DateTime update_date { get; set; }
        public string maintainer { get; set; }
        public string maintainer_tel { get; set; }
        public Nullable<System.DateTime> new_begin_date { get; set; }
        public Nullable<System.DateTime> new_end_date { get; set; }
        public int new_icon { get; set; }
        public string tag_text { get; set; }
        public string keyword { get; set; }
    }
}
