//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_promote
    {
        public int ps_p_id { get; set; }
        public int promote_id { get; set; }
        public string promote_name { get; set; }
        public string promote_department { get; set; }
        public System.DateTime bgn_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string memo { get; set; }
        public int promote_leader_id { get; set; }
        public int serial_no { get; set; }
    }
}
