//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_promote_work
    {
        public int work_id { get; set; }
        public int promote_id { get; set; }
        public string depart_code { get; set; }
        public System.DateTime work_date { get; set; }
        public decimal work_hour { get; set; }
        public string work_content { get; set; }
        public int operators_id { get; set; }
    }
}
