//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_survey_record
    {
        public int r_id { get; set; }
        public int s_id { get; set; }
        public System.DateTime fill_date { get; set; }
        public int staff_id { get; set; }
        public string fill_ip { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
