//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cs_video
    {
        public int video_id { get; set; }
        public string video_kind { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string enabled { get; set; }
        public System.DateTime begin_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string thumb_name { get; set; }
        public byte[] thumb_content { get; set; }
        public string video_name { get; set; }
        public byte[] video_content { get; set; }
        public int video_count { get; set; }
        public string maintainer { get; set; }
        public string maintainer_tel { get; set; }
        public int update_user_id { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
