//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cs_ap_update> cs_ap_update { get; set; }
        public virtual DbSet<cs_ap_update_file> cs_ap_update_file { get; set; }
        public virtual DbSet<cs_ap_update_vs_demand> cs_ap_update_vs_demand { get; set; }
        public virtual DbSet<cs_ap_version> cs_ap_version { get; set; }
        public virtual DbSet<cs_ap_version_file> cs_ap_version_file { get; set; }
        public virtual DbSet<cs_authority> cs_authority { get; set; }
        public virtual DbSet<cs_authority_menu> cs_authority_menu { get; set; }
        public virtual DbSet<cs_code> cs_code { get; set; }
        public virtual DbSet<cs_code_kind> cs_code_kind { get; set; }
        public virtual DbSet<cs_contract> cs_contract { get; set; }
        public virtual DbSet<cs_contract_file> cs_contract_file { get; set; }
        public virtual DbSet<cs_demand> cs_demand { get; set; }
        public virtual DbSet<cs_demand_dispatch> cs_demand_dispatch { get; set; }
        public virtual DbSet<cs_demand_file> cs_demand_file { get; set; }
        public virtual DbSet<cs_department> cs_department { get; set; }
        public virtual DbSet<cs_department_contact> cs_department_contact { get; set; }
        public virtual DbSet<cs_department_envir> cs_department_envir { get; set; }
        public virtual DbSet<cs_department_file> cs_department_file { get; set; }
        public virtual DbSet<cs_holiday> cs_holiday { get; set; }
        public virtual DbSet<cs_log> cs_log { get; set; }
        public virtual DbSet<cs_menu> cs_menu { get; set; }
        public virtual DbSet<cs_news> cs_news { get; set; }
        public virtual DbSet<cs_news_file> cs_news_file { get; set; }
        public virtual DbSet<cs_news_file_types> cs_news_file_types { get; set; }
        public virtual DbSet<cs_promote> cs_promote { get; set; }
        public virtual DbSet<cs_promote_file> cs_promote_file { get; set; }
        public virtual DbSet<cs_promote_work> cs_promote_work { get; set; }
        public virtual DbSet<cs_qa> cs_qa { get; set; }
        public virtual DbSet<cs_qa_file> cs_qa_file { get; set; }
        public virtual DbSet<cs_question> cs_question { get; set; }
        public virtual DbSet<cs_question_dispatch> cs_question_dispatch { get; set; }
        public virtual DbSet<cs_question_file> cs_question_file { get; set; }
        public virtual DbSet<cs_staff_1060428> cs_staff_1060428 { get; set; }
        public virtual DbSet<cs_survey> cs_survey { get; set; }
        public virtual DbSet<cs_survey_answer> cs_survey_answer { get; set; }
        public virtual DbSet<cs_survey_answer_record> cs_survey_answer_record { get; set; }
        public virtual DbSet<cs_survey_record> cs_survey_record { get; set; }
        public virtual DbSet<cs_survey_topic> cs_survey_topic { get; set; }
        public virtual DbSet<cs_survey_user> cs_survey_user { get; set; }
        public virtual DbSet<cs_use_authority> cs_use_authority { get; set; }
        public virtual DbSet<cs_user> cs_user { get; set; }
        public virtual DbSet<cs_userXX> cs_userXX { get; set; }
        public virtual DbSet<cs_video> cs_video { get; set; }
        public virtual DbSet<psdcode> psdcode { get; set; }
        public virtual DbSet<psproject> psproject { get; set; }
        public virtual DbSet<psstaff> psstaff { get; set; }
        public virtual DbSet<xx_path> xx_path { get; set; }
        public virtual DbSet<cs_contract_20201014> cs_contract_20201014 { get; set; }
        public virtual DbSet<cs_demand_20201014> cs_demand_20201014 { get; set; }
        public virtual DbSet<cs_department_20201014> cs_department_20201014 { get; set; }
        public virtual DbSet<cs_department_20201208> cs_department_20201208 { get; set; }
        public virtual DbSet<cs_menu_1100126> cs_menu_1100126 { get; set; }
        public virtual DbSet<cs_news_20201014> cs_news_20201014 { get; set; }
        public virtual DbSet<cs_question_20201014> cs_question_20201014 { get; set; }
        public virtual DbSet<cs_user_1060428> cs_user_1060428 { get; set; }
        public virtual DbSet<cs_user_20201014> cs_user_20201014 { get; set; }
        public virtual DbSet<uvw_cs_user> uvw_cs_user { get; set; }
    
        [DbFunction("Entities", "udf_date")]
        public virtual IQueryable<udf_date_Result> udf_date(Nullable<System.DateTime> date_begin, Nullable<System.DateTime> date_end)
        {
            var date_beginParameter = date_begin.HasValue ?
                new ObjectParameter("date_begin", date_begin) :
                new ObjectParameter("date_begin", typeof(System.DateTime));
    
            var date_endParameter = date_end.HasValue ?
                new ObjectParameter("date_end", date_end) :
                new ObjectParameter("date_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_date_Result>("[Entities].[udf_date](@date_begin, @date_end)", date_beginParameter, date_endParameter);
        }
    
        [DbFunction("Entities", "udf_holiday")]
        public virtual IQueryable<udf_holiday_Result> udf_holiday(Nullable<System.DateTime> date_begin, Nullable<System.DateTime> date_end)
        {
            var date_beginParameter = date_begin.HasValue ?
                new ObjectParameter("date_begin", date_begin) :
                new ObjectParameter("date_begin", typeof(System.DateTime));
    
            var date_endParameter = date_end.HasValue ?
                new ObjectParameter("date_end", date_end) :
                new ObjectParameter("date_end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_holiday_Result>("[Entities].[udf_holiday](@date_begin, @date_end)", date_beginParameter, date_endParameter);
        }
    
        [DbFunction("Entities", "udf_promote")]
        public virtual IQueryable<udf_promote_Result> udf_promote(Nullable<int> promote_id)
        {
            var promote_idParameter = promote_id.HasValue ?
                new ObjectParameter("promote_id", promote_id) :
                new ObjectParameter("promote_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_promote_Result>("[Entities].[udf_promote](@promote_id)", promote_idParameter);
        }
    
        public virtual int usp_open_symmetric()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_open_symmetric");
        }
    }
}
