//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psdcode
    {
        public string KIND { get; set; }
        public string CODE { get; set; }
        public string VALUE { get; set; }
        public short SERIAL_NO { get; set; }
        public string EXTENDED { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USERID { get; set; }
    }
}
