//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class psproject
    {
        public int P_ID { get; set; }
        public string P_KIND { get; set; }
        public string P_TYPE { get; set; }
        public string P_NO { get; set; }
        public string YR { get; set; }
        public string P_NAME { get; set; }
        public Nullable<int> P_PRINCIPAL { get; set; }
        public string ORGANIZE { get; set; }
        public string CUSTOMER { get; set; }
        public decimal AMT { get; set; }
        public Nullable<decimal> AMT_AWARD { get; set; }
        public string AWARD_DATE { get; set; }
        public int PROJECT_MAN_MONTH { get; set; }
        public string P_BYM { get; set; }
        public string P_EYM { get; set; }
        public string WARRANTY_BYM { get; set; }
        public string WARRANTY_EYM { get; set; }
        public Nullable<decimal> BID_BOND { get; set; }
        public string CONTRACT_PAYMENT_KIND { get; set; }
        public Nullable<decimal> CONTRACT_BOND { get; set; }
        public string CONTRACT_RETURN_DATE { get; set; }
        public string CONTRACT_RETRIEVE_DATE { get; set; }
        public string WTY_PAYMENT_KIND { get; set; }
        public Nullable<decimal> WTY_BOND { get; set; }
        public string WTY_RETURN_DATE { get; set; }
        public string WTY_RETRIEVE_DATE { get; set; }
        public string INVOICE_KIND { get; set; }
        public string UNIFIED_BUSINESS_NO { get; set; }
        public string CUSTOMER_REPR { get; set; }
        public string CUSTOMER_ADDR { get; set; }
        public string CUSTOMER_TEL { get; set; }
        public string P_MEMO { get; set; }
        public string UPDATE_USERID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
