//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_cs_user
    {
        public int staff_id { get; set; }
        public string apply_department { get; set; }
        public string user_code { get; set; }
        public string staff_name { get; set; }
        public string title { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string is_contact { get; set; }
        public byte[] password { get; set; }
        public string change_password { get; set; }
        public string duty { get; set; }
        public string signin { get; set; }
        public string enabled { get; set; }
        public short error_count { get; set; }
        public Nullable<System.DateTime> last_login_time { get; set; }
        public string memo { get; set; }
        public int update_user_id { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
