//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xx_path
    {
        public int id { get; set; }
        public string path { get; set; }
        public Nullable<int> menu_id { get; set; }
        public Nullable<int> file_id { get; set; }
        public Nullable<int> file_type_id { get; set; }
    }
}
